"""Format-sniffer bench: every SigMF datatype, test signal and level, scored against the truth.

Run `uv run python -m bench.sniffer` to write bench/results/sniffer.{json,md}. The gate is that
the sniffer never proposes a wrong format and never leaves the truth out of an UNKNOWN's
candidates; the one accepted cost is real data proposed as complex under the stated convention.
"""

import json
from collections import Counter
from collections.abc import Callable, Iterator
from dataclasses import dataclass
from pathlib import Path

import numpy as np

from dsp.evidence import EvidenceLevel
from dsp.ingest.formats import ALL_DATATYPES, SampleFormat
from dsp.ingest.sniff import BLOCK_BYTES, LAYOUT_MARGIN, TIE_MARGIN, sniff_blocks, twin
from dsp.synth.waveforms import awgn, frequency_shift, fsk, psk_symbols, shape, tone

RESULTS = Path(__file__).resolve().parents[2] / "results"
SEEDS = (1, 2, 3)
SAMPLES = 16384

Signal = Callable[[np.random.Generator, int], np.ndarray]


def _qpsk(sps: int, offset: float, snr_db: float) -> Signal:
    def make(rng: np.random.Generator, n: int) -> np.ndarray:
        x = shape(psk_symbols(rng, n // sps + 1, 4), sps, 0.35)[:n]
        return frequency_shift(x, offset) + awgn(rng, n, 10 ** (-snr_db / 10))

    return make


COMPLEX_SIGNALS: dict[str, Signal] = {
    "noise": lambda rng, n: awgn(rng, n),
    "qpsk, 4 sps, centred": _qpsk(4, 0.0, 25),
    "qpsk, 2 sps, offset 0.2": _qpsk(2, 0.2, 20),
    "narrowband qpsk at 0 dB SNR": _qpsk(16, -0.3, 0),
    "tone in noise": lambda rng, n: tone(n, 0.013) + awgn(rng, n, 0.1),
    "2-fsk, 8 sps": lambda rng, n: fsk(rng, n // 8 + 1, 2, 8, 0.05)[:n] + awgn(rng, n, 0.01),
}
REAL_SIGNALS: dict[str, Signal] = {
    "noise": lambda rng, n: rng.standard_normal(n),
    "am audio tone": lambda rng, n: (
        np.sin(2 * np.pi * 0.01 * np.arange(n))
        * (1 + 0.5 * np.sin(2 * np.pi * 0.0003 * np.arange(n)))
        + 0.1 * rng.standard_normal(n)
    ),
    "real if qpsk at 0.2": lambda rng, n: np.real(_qpsk(4, 0.2, 25)(rng, n)),
}


def levels_dbfs(fmt: SampleFormat) -> tuple[float, ...]:
    """RMS levels that span how each format is used; floats are relative to 1.0."""
    if fmt.kind == "f":
        return (0.0, -40.0, 20.0)
    return {8: (-12.0, -24.0), 16: (-20.0, -50.0), 32: (-20.0, -90.0)}[fmt.bits]


@dataclass(frozen=True)
class Case:
    datatype: str
    signal: str
    level_dbfs: float
    seed: int
    data: bytes


def corpus(seeds: tuple[int, ...] = SEEDS, samples: int = SAMPLES) -> Iterator[Case]:
    for seed in seeds:
        for datatype in ALL_DATATYPES:
            fmt = SampleFormat.parse(datatype)
            signals = COMPLEX_SIGNALS if fmt.is_complex else REAL_SIGNALS
            for name, make in signals.items():
                for level in levels_dbfs(fmt):
                    rng = np.random.default_rng([seed, ALL_DATATYPES.index(datatype)])
                    x = make(rng, samples)
                    x = x / np.sqrt(np.mean(np.abs(x) ** 2)) * 10 ** (level / 20)
                    yield Case(datatype, name, level, seed, fmt.encode(x))


def outcome(case: Case) -> str:
    data = case.data
    blocks = [data[i : i + BLOCK_BYTES] for i in range(0, len(data), BLOCK_BYTES)]
    param = sniff_blocks(blocks).datatype
    if param.level is EvidenceLevel.UNKNOWN:
        alternatives = {a.value for a in param.alternatives}
        return (
            "ambiguous, truth listed" if case.datatype in alternatives else "FAIL: truth not listed"
        )
    if param.value == case.datatype:
        return "correct, layout by convention" if param.warnings else "correct"
    if param.value == twin(case.datatype) and param.warnings and case.datatype[0] == "r":
        return "real proposed as complex by convention"
    return "FAIL: wrong format"


def run(seeds: tuple[int, ...] = SEEDS) -> dict[str, Counter[str]]:
    table: dict[str, Counter[str]] = {d: Counter() for d in ALL_DATATYPES}
    for case in corpus(seeds):
        table[case.datatype][outcome(case)] += 1
    return table


OUTCOMES = (
    "correct",
    "correct, layout by convention",
    "real proposed as complex by convention",
    "ambiguous, truth listed",
    "FAIL: truth not listed",
    "FAIL: wrong format",
)


def render(table: dict[str, Counter[str]], seeds: tuple[int, ...]) -> str:
    total = Counter[str]()
    for counts in table.values():
        total.update(counts)
    n = sum(total.values())
    lines = [
        "# Format sniffer bench",
        "",
        "Generated by `uv run python -m bench.sniffer`; do not edit by hand.",
        "",
        f"Each SigMF datatype with {len(COMPLEX_SIGNALS)} complex or {len(REAL_SIGNALS)} real test "
        f"signals, at 2 or 3 RMS levels, for seeds {list(seeds)}: {n} files of {SAMPLES} samples. "
        f"Tie margins: {TIE_MARGIN} bits/byte between formats whose components differ; "
        f"{LAYOUT_MARGIN} bits of prediction gain per component between the real and complex "
        "readings of the same components.",
        "",
        "Complex signals: " + "; ".join(COMPLEX_SIGNALS) + ".",
        "Real signals: " + "; ".join(REAL_SIGNALS) + ".",
        "",
        "## Totals",
        "",
        "| Outcome | Files | Share |",
        "|---|---:|---:|",
        *(f"| {o} | {total[o]} | {total[o] / n:.1%} |" for o in OUTCOMES),
        "",
        "## Per datatype",
        "",
        "| Truth | " + " | ".join(OUTCOMES) + " |",
        "|---|" + "---:|" * len(OUTCOMES),
        *(
            f"| {d} | " + " | ".join(str(table[d][o]) for o in OUTCOMES) + " |"
            for d in ALL_DATATYPES
        ),
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    table = run(SEEDS)
    RESULTS.mkdir(exist_ok=True)
    (RESULTS / "sniffer.md").write_text(render(table, SEEDS), encoding="utf-8", newline="\n")
    data = {
        "seeds": list(SEEDS),
        "samples": SAMPLES,
        "outcomes": {d: dict(c) for d, c in table.items()},
    }
    (RESULTS / "sniffer.json").write_text(
        json.dumps(data, indent=2, sort_keys=True) + "\n", encoding="utf-8", newline="\n"
    )
    failures = sum(c[o] for c in table.values() for o in OUTCOMES if o.startswith("FAIL"))
    print(f"wrote {RESULTS / 'sniffer.md'}; failures: {failures}")
    return 1 if failures else 0


if __name__ == "__main__":
    raise SystemExit(main())
