import { useEffect, useState } from 'react'
import { Check, FlaskConical, Loader2, Upload, WifiOff } from 'lucide-react'
import { BRAND } from '@/brand'
import { listSamples, type SampleInfo } from '@/lib/api'
import { LEVEL_INFO, type EvidenceLevel } from '@/lib/evidence'
import { EvidenceBadge } from './EvidenceBadge'
import { Logo } from './Logo'

/** What a visitor should look for in each bundled sample, by id. The ground truth behind each is
 * in `data/demo/<id>.truth.json`; the server's own title and description come from `/samples`. */
interface SampleNote {
  /** What the PS asks for that this sample shows, as short chips. */
  covers: readonly string[]
  /** What to look for. */
  sees: readonly string[]
}

const SAMPLE_NOTES: Record<string, SampleNote> = {
  scene: {
    covers: ['Detection', 'QPSK / BPSK', 'Convolutional + Viterbi', 'Framing'],
    sees: [
      'Two coded signals recovered, their frames proven by CRC',
      'One noisy signal left undecoded, with the reason why',
      'An FM broadcast labelled analog, not forced into a digital label',
    ],
  },
  scene_coverage: {
    covers: ['16QAM', 'Helical + convolutional interleavers', 'Blind code identification'],
    sees: [
      '16QAM through a helical (diagonal) interleaver, undone and proven',
      'A convolutional (Forney) interleaver found on a QPSK signal',
      'A K=9 convolutional code that is not in any catalogue, found blind',
      'Frame payloads that read as text in the Frames and Bit stream tabs',
    ],
  },
  scene_widen: {
    covers: ['8PSK', 'Block interleaver', 'Reed-Solomon', 'Concatenated codes'],
    sees: [
      'Block de-interleaving found and undone on an 8PSK signal',
      'Reed-Solomon outer code peeled off a QPSK signal',
    ],
  },
  scene_fsk: {
    covers: ['2-FSK', 'Symbol rate'],
    sees: ['Tone-based demodulation of a 2-FSK signal', 'Symbol rate estimated, frames proven by CRC'],
  },
  scene_fsk4: {
    covers: ['4-FSK'],
    sees: ['Four tones told apart, two bits per symbol', 'Frames proven by CRC, payload readable as text'],
  },
  scene_ldpc: {
    covers: ['LDPC'],
    sees: [
      'An LDPC code named from a catalogue of published codes',
      'Proven by the frame CRC, with every other candidate in the ledger',
    ],
  },
  scene_systems: {
    covers: ['Known systems', 'POCSAG', 'NAVTEX', 'AIS'],
    sees: [
      'Three public systems recognised blind, each proved by its own check',
      'The paging messages and the NAVTEX warning shown as text',
      'AIS packets proved by CRC-16, with the ship identities',
    ],
  },
  scene_wav: {
    covers: ['.wav input', 'Sample rate from the header'],
    sees: ['A stereo WAV read as I and Q, its rate taken from the header', 'Frames proven by CRC'],
  },
  scene_raw: {
    covers: ['Raw .iq input', 'Sample rate unknown'],
    sees: [
      'A headerless file opened with its sample rate UNKNOWN, and Sanket asks for it',
      'Enter 1 MS/s and the signal decodes and is proven',
    ],
  },
}

const LEVELS: readonly EvidenceLevel[] = ['VERIFIED', 'MEASURED', 'ESTIMATED', 'HYPOTHESIS', 'UNKNOWN']

function megabytes(bytes: number): string {
  return `${(bytes / 1024 ** 2).toFixed(1)} MB`
}

interface Props {
  /** A recording is being opened (a sample, a path or an upload). */
  opening: boolean
  /** Which sample card was clicked, while it opens. */
  openingSample: string | null
  onUpload: (files: File[]) => void
  onOpenSample: (id: string) => void
}

type Samples = { state: 'loading' } | { state: 'ready'; items: SampleInfo[] } | { state: 'error'; message: string }

/**
 * What the workspace shows until a recording is open: one primary action (open a file) and the
 * bundled sample recordings, so nobody meets a blank screen. Every sample is labelled synthetic:
 * it was generated by Sanket's ground-truth lab, so the answers can be checked.
 */
export function StartScreen({ opening, openingSample, onUpload, onOpenSample }: Props) {
  const [samples, setSamples] = useState<Samples>({ state: 'loading' })

  useEffect(() => {
    let live = true
    listSamples()
      .then((items) => live && setSamples({ state: 'ready', items }))
      .catch((e: unknown) => live && setSamples({ state: 'error', message: e instanceof Error ? e.message : String(e) }))
    return () => {
      live = false
    }
  }, [])

  return (
    <main
      aria-label="Start"
      data-testid="start-screen"
      className="relative min-h-0 flex-1 overflow-y-auto bg-background"
    >
      <div className="mx-auto flex w-full max-w-5xl flex-col gap-6 2xl:max-w-7xl px-6 py-6 max-sm:px-4">
        <header className="flex items-start gap-4">
          <Logo className="size-11 shrink-0" />
          <div className="min-w-0">
            <p className="eyebrow">{BRAND.tagline}</p>
            <h1 className="mt-0.5 text-xl font-semibold tracking-tight">What is in this recording?</h1>
            <p className="mt-1 max-w-3xl text-sm text-muted-foreground">
              Give Sanket an unknown radio recording. It works out how the signal was sent (rate, modulation,
              interleaving, error correction, framing), undoes each layer to recover the bits, and shows the
              evidence for every claim.
            </p>
          </div>
        </header>

        <section aria-labelledby="start-samples">
          <div className="mb-3 flex flex-wrap items-baseline gap-x-3 gap-y-1">
            <h2 id="start-samples" className="text-[15px] font-semibold">
              Or try a sample
            </h2>
            <p className="text-xs text-muted-foreground">
              Synthetic recordings with known answers. Analysis runs in the background and takes from a few seconds to
              about half a minute.
            </p>
          </div>

          {samples.state === 'loading' && (
            <p role="status" className="text-xs text-muted-foreground italic">
              Looking for the bundled samples…
            </p>
          )}
          {samples.state === 'error' && (
            <p role="alert" className="text-xs text-destructive">
              Could not list the samples: {samples.message}
            </p>
          )}
          {samples.state === 'ready' && samples.items.length === 0 && (
            <p className="text-xs text-muted-foreground italic">
              No sample recordings are installed. Run <span className="num">tools/make_demo.py</span> to generate them,
              or open your own recording above.
            </p>
          )}
          {samples.state === 'ready' && samples.items.length > 0 && (
            <ul className="grid grid-cols-2 gap-3 max-md:grid-cols-1 2xl:grid-cols-3">
              {samples.items.map((s) => {
                const busy = openingSample === s.id
                const note = SAMPLE_NOTES[s.id]
                return (
                  <li key={s.id} className="flex">
                    <button
                      type="button"
                      onClick={() => onOpenSample(s.id)}
                      disabled={opening}
                      data-sample={s.id}
                      className="group flex w-full flex-col gap-2 rounded-lg border bg-surface p-3.5 text-left transition-colors enabled:hover:border-primary/60 enabled:hover:bg-surface-2/60 disabled:opacity-60"
                    >
                      <span className="flex items-start justify-between gap-2">
                        <span className="text-sm font-semibold">{s.title}</span>
                        <span className="flex shrink-0 items-center gap-1 rounded-[3px] border border-dashed border-border-strong px-1.5 text-2xs font-medium text-muted-foreground uppercase">
                          <FlaskConical className="size-3" aria-hidden />
                          Synthetic
                        </span>
                      </span>
                      <span className="text-xs text-muted-foreground">{s.description}</span>
                      {note && (
                        <span className="flex flex-wrap gap-1">
                          {note.covers.map((c) => (
                            <span
                              key={c}
                              className="rounded-[3px] bg-surface-2 px-1.5 py-px text-2xs font-medium text-muted-foreground"
                            >
                              {c}
                            </span>
                          ))}
                        </span>
                      )}
                      {note && (
                        <span className="flex flex-col gap-1">
                          <span className="eyebrow">What you will see</span>
                          {note.sees.map((n) => (
                            <span key={n} className="flex items-start gap-1.5 text-xs">
                              <Check className="mt-[3px] size-3 shrink-0 text-primary" aria-hidden />
                              {n}
                            </span>
                          ))}
                        </span>
                      )}
                      <span className="mt-auto flex items-center justify-between pt-1 text-2xs text-subtle-foreground">
                        <span className="num">
                          {s.signals} {s.signals === 1 ? 'signal' : 'signals'} · {megabytes(s.sizeBytes)}
                        </span>
                        <span className="flex items-center gap-1 text-xs font-medium text-primary">
                          {busy ? (
                            <>
                              <Loader2 className="size-3.5 animate-spin motion-reduce:animate-none" aria-hidden />
                              Opening…
                            </>
                          ) : (
                            'Open sample →'
                          )}
                        </span>
                      </span>
                    </button>
                  </li>
                )
              })}
            </ul>
          )}
        </section>

        <section aria-labelledby="start-open" className="rounded-lg border border-dashed border-border-strong bg-surface p-4">
          <div className="flex flex-wrap items-center gap-4">
            <div className="min-w-0 flex-1">
              <h2 id="start-open" className="text-[15px] font-semibold">
                Open your own recording
              </h2>
              <p className="mt-0.5 text-xs text-muted-foreground">
                .iq / raw, .wav, SigMF, .npy and more. Drop files anywhere on this window, choose them here, or paste
                a path into the box at the top. Nothing leaves this machine.
              </p>
            </div>
            <label
              className={`flex shrink-0 items-center gap-2 rounded-md bg-primary px-3.5 py-2 text-sm font-medium text-primary-foreground focus-within:ring-2 focus-within:ring-ring focus-within:ring-offset-2 focus-within:ring-offset-surface ${
                opening ? 'opacity-50' : 'cursor-pointer hover:opacity-90'
              }`}
            >
              <Upload className="size-4" aria-hidden />
              Choose files
              <input
                type="file"
                multiple
                disabled={opening}
                className="sr-only"
                aria-label="Choose recording files"
                onChange={(e) => {
                  const files = Array.from(e.target.files ?? [])
                  e.target.value = '' // so choosing the same file again fires change
                  if (files.length > 0) onUpload(files)
                }}
              />
            </label>
          </div>
        </section>

        <footer className="flex flex-col gap-3 border-t pt-5">
          <div>
            <h2 className="eyebrow mb-2">How sure is Sanket? Every value carries one of five levels</h2>
            <ul className="grid grid-cols-5 gap-3 max-lg:grid-cols-2 max-sm:grid-cols-1">
              {LEVELS.map((level) => (
                <li key={level} className="flex flex-col items-start gap-1">
                  <EvidenceBadge level={level} />
                  <span className="text-xs text-muted-foreground">{LEVEL_INFO[level].meaning}</span>
                </li>
              ))}
            </ul>
          </div>
          <p className="flex items-center gap-1.5 text-2xs text-subtle-foreground">
            <WifiOff className="size-3" aria-hidden />
            Runs fully offline: fonts, code and data are bundled, and no recording leaves this machine.
          </p>
        </footer>
      </div>
    </main>
  )
}
