import { useState, type FormEvent } from 'react'
import { FileAudio, FolderOpen, Moon, Sun, Upload, WifiOff } from 'lucide-react'
import { BRAND } from '@/brand'
import { useTheme } from '@/hooks/theme'
import { VIEWS, type ViewId } from '@/lib/views'
import type { RecordingInfo } from '@/lib/api'
import type { ResultFormat } from '@/lib/exports'
import { Logo } from './Logo'
import { ResultsExports } from './ResultsExports'

interface Props {
  fileName: string
  isDemo: boolean
  /** A recording whose file states it was generated by dsp.synth. */
  synthetic: boolean
  opening: boolean
  openError: string | null
  view: ViewId
  onViewChange: (view: ViewId) => void
  /** `sequence` reads numbered files (rec_000, rec_001, ...) as one recording. */
  onOpen: (path: string, sequence: boolean) => void
  /** Files chosen from the picker (a SigMF pair arrives as two); dropped files reach App directly. */
  onUpload: (files: File[]) => void
  onOpenSettings: () => void
  /** Where the finished analysis' results download from, by format; absent for the demo and
   * while the analysis is still running (the server holds a partial analysis back). */
  resultsUrl?: (format: ResultFormat) => string
  /** What SigMF output the recording supports; the SigMF link and Save as SigMF follow it. */
  sigmf?: RecordingInfo['sigmf']
  /** Save as SigMF for a raw file: resolves to the path written, rejects with the server's text. */
  onSaveSigmf?: () => Promise<string>
}

export function TopBar({
  fileName,
  isDemo,
  synthetic,
  opening,
  openError,
  view,
  onViewChange,
  onOpen,
  onUpload,
  onOpenSettings,
  resultsUrl,
  sigmf = 'none',
  onSaveSigmf,
}: Props) {
  const { theme, toggle } = useTheme()
  const [path, setPath] = useState('')
  const [sequence, setSequence] = useState(false)

  function submit(e: FormEvent) {
    e.preventDefault()
    const trimmed = path.trim()
    if (trimmed && !opening) onOpen(trimmed, sequence)
  }

  return (
    <header className="flex h-12 shrink-0 items-center gap-3 border-b bg-surface px-3">
      <div className="flex items-center gap-2.5">
        <Logo className="size-7" />
        <div className="flex items-baseline gap-2">
          <span className="text-[15px] font-semibold tracking-tight">{BRAND.name}</span>
          <span lang="hi" className="font-deva text-xs text-subtle-foreground max-sm:hidden">
            {BRAND.nativeName}
          </span>
        </div>
      </div>

      <div className="h-5 w-px bg-border max-sm:hidden" aria-hidden />

      <nav aria-label="Workspace section" className="flex shrink-0 items-center gap-0.5 max-md:hidden">
        {VIEWS.map((v) => {
          const selected = v.id === view
          
          return (
            <button
              key={v.id}
              type="button"
              onClick={() => {
                if (v.id === 'assumptions') {
                  onOpenSettings()
                } else {
                  onViewChange(v.id)
                }
              }}
              aria-current={selected ? 'page' : undefined}
              title={`${v.hint} (Alt+${v.digit})`}
              className={`rounded-md px-2.5 py-1 text-xs font-medium tracking-wide uppercase transition-colors ${
                selected ? 'bg-surface-2 text-foreground' : 'text-muted-foreground hover:bg-surface-2/60 hover:text-foreground'
              }`}
            >
              {v.label}
            </button>
          )
        })}
      </nav>

      <div className="h-5 w-px bg-border max-sm:hidden" aria-hidden />

      <div className="flex min-w-0 items-center gap-2">
        <FileAudio className="size-4 shrink-0 text-muted-foreground" aria-hidden />
        <span className="num truncate text-xs">{fileName}</span>
        <span className="shrink-0 rounded-[3px] border border-dashed border-border-strong px-1.5 text-2xs font-medium text-muted-foreground uppercase">
          {isDemo ? 'Synthetic demo' : synthetic ? 'Synthetic recording' : 'Real recording'}
        </span>
      </div>

      <form onSubmit={submit} className="flex min-w-0 items-center gap-1.5 max-lg:hidden">
        <label htmlFor="open-path" className="sr-only">
          Open a recording by path
        </label>
        <input
          id="open-path"
          type="text"
          value={path}
          onChange={(e) => setPath(e.target.value)}
          placeholder="Open a recording by path…"
          className="w-56 rounded-md border border-border-strong bg-surface px-2 py-1 text-xs text-foreground placeholder:text-subtle-foreground"
        />
        <button
          type="submit"
          disabled={opening || !path.trim()}
          className="flex shrink-0 items-center gap-1 rounded-md border border-border-strong px-2 py-1 text-xs font-medium text-muted-foreground enabled:hover:bg-surface-2 enabled:hover:text-foreground disabled:opacity-40"
        >
          <FolderOpen className="size-3.5" aria-hidden />
          {opening ? 'Opening…' : 'Open'}
        </button>
        <label
          className="flex shrink-0 items-center gap-1 text-xs text-muted-foreground"
          title="Read numbered files (rec_000.cu8, rec_001.cu8, ...) as one recording. A folder is opened as a list of its recordings."
        >
          <input type="checkbox" checked={sequence} onChange={(e) => setSequence(e.target.checked)} />
          Join numbered files
        </label>
        <label
          className={`flex shrink-0 items-center gap-1 rounded-md border border-border-strong px-2 py-1 text-xs font-medium text-muted-foreground focus-within:ring-2 focus-within:ring-ring ${
            opening ? 'opacity-40' : 'cursor-pointer hover:bg-surface-2 hover:text-foreground'
          }`}
          title="Copy recording files into the workspace and open them. Drop files on the window works too."
        >
          <Upload className="size-3.5" aria-hidden />
          Upload
          <input
            type="file"
            multiple
            disabled={opening}
            className="sr-only"
            aria-label="Upload recording files"
            onChange={(e) => {
              const files = Array.from(e.target.files ?? [])
              e.target.value = '' // so choosing the same file again fires change
              if (files.length > 0) onUpload(files)
            }}
          />
        </label>
      </form>
      {openError && (
        <span role="alert" className="max-w-[24ch] truncate text-xs text-destructive" title={openError}>
          {openError}
        </span>
      )}

      <div className="ml-auto flex items-center gap-2">
        {resultsUrl && (
          <ResultsExports
            resultsUrl={resultsUrl}
            sigmf={sigmf}
            onSaveSigmf={onSaveSigmf ?? (() => Promise.reject(new Error('Save as SigMF is not available')))}
          />
        )}
        <span
          className="flex items-center gap-1.5 rounded-full border px-2 py-0.5 text-2xs font-medium text-muted-foreground max-md:hidden"
          title="This build loads nothing from the network: fonts, code and data are all bundled."
        >
          <WifiOff className="size-3" aria-hidden />
          Offline build
        </span>
        <button
          type="button"
          onClick={toggle}
          className="grid size-8 place-items-center rounded-md text-muted-foreground hover:bg-surface-2 hover:text-foreground"
          aria-label={theme === 'dark' ? 'Switch to light theme' : 'Switch to dark theme'}
        >
          {theme === 'dark' ? <Sun className="size-4" /> : <Moon className="size-4" />}
        </button>
      </div>
    </header>
  )
}
