import { useState, type FormEvent } from 'react'
import { CircleHelp, FileAudio, FolderOpen, Loader2, Moon, Sun, Upload, WifiOff } from 'lucide-react'
import { BRAND } from '@/brand'
import { useTheme } from '@/hooks/theme'
import { VIEWS, type SectionId } from '@/lib/views'
import type { RecordingInfo } from '@/lib/api'
import type { ResultFormat } from '@/lib/exports'
import { Logo } from './Logo'
import { ResultsExports } from './ResultsExports'

interface Props {
  /** The open recording's name; null on the start screen. */
  fileName: string | null
  /** A recording whose file states it was generated by dsp.synth. */
  synthetic: boolean
  opening: boolean
  /** How far the background analysis has got, while it runs. */
  progress?: { done: number; total: number }
  view: SectionId
  onViewChange: (view: SectionId) => void
  /** Reopens the welcome dialog (and from it the tour). */
  onHelp: () => void
  /** `sequence` reads numbered files (rec_000, rec_001, ...) as one recording. */
  onOpen: (path: string, sequence: boolean) => void
  /** Files chosen from the picker (a SigMF pair arrives as two); dropped files reach App directly. */
  onUpload: (files: File[]) => void
  onOpenSettings: () => void
  /** Where the finished analysis' results download from, by format; absent while the analysis is
   * still running (the server holds a partial analysis back). */
  resultsUrl?: (format: ResultFormat) => string
  /** What SigMF output the recording supports; the SigMF link and Save as SigMF follow it. */
  sigmf?: RecordingInfo['sigmf']
  /** Save as SigMF for a raw file: resolves to the path written, rejects with the server's text. */
  onSaveSigmf?: () => Promise<string>
}

export function TopBar({
  fileName,
  synthetic,
  opening,
  progress,
  view,
  onViewChange,
  onHelp,
  onOpen,
  onUpload,
  onOpenSettings,
  resultsUrl,
  sigmf = 'none',
  onSaveSigmf,
}: Props) {
  const { theme, toggle } = useTheme()
  const [path, setPath] = useState('')
  const [sequence, setSequence] = useState(false)

  function submit(e: FormEvent) {
    e.preventDefault()
    const trimmed = path.trim()
    if (trimmed && !opening) onOpen(trimmed, sequence)
  }

  return (
    <header className="relative flex h-12 shrink-0 items-center gap-3 border-b bg-surface px-3">
      {progress && progress.total > 0 && (
        <div
          role="progressbar"
          aria-label="Analysis progress"
          aria-valuemin={0}
          aria-valuemax={progress.total}
          aria-valuenow={progress.done}
          className="absolute inset-x-0 bottom-0 h-0.5 bg-transparent"
        >
          <div
            className="h-full bg-primary transition-[width] duration-500"
            style={{ width: `${Math.max(4, (progress.done / progress.total) * 100)}%` }}
          />
        </div>
      )}
      <div className="flex items-center gap-2.5">
        <Logo className="size-7" />
        <div className="flex items-baseline gap-2">
          <span className="text-[15px] font-semibold tracking-tight">{BRAND.name}</span>
          <span lang="hi" className="font-deva text-xs text-subtle-foreground max-xl:hidden">
            {BRAND.nativeName}
          </span>
        </div>
      </div>

      <div className="h-5 w-px bg-border max-xl:hidden" aria-hidden />

      <nav aria-label="Workspace section" data-tour="section-nav" className="flex shrink-0 items-center gap-0.5 max-md:hidden">
        {VIEWS.filter((v) => fileName !== null || v.id === 'survey' || v.id === 'history').map((v) => {
          const selected = v.id === view

          return (
            <button
              key={v.id}
              type="button"
              onClick={() => {
                if (v.id === 'assumptions') onOpenSettings()
                else onViewChange(v.id)
              }}
              aria-current={selected ? 'page' : undefined}
              data-tour={v.id === 'assumptions' ? 'assumptions' : undefined}
              title={`${v.hint} (Alt+${v.digit})`}
              className={`rounded-md px-2.5 py-1 text-xs font-medium tracking-wide uppercase transition-colors max-xl:px-1.5 max-xl:tracking-normal ${
                selected ? 'bg-surface-2 text-foreground' : 'text-muted-foreground hover:bg-surface-2/60 hover:text-foreground'
              }`}
            >
              {v.label}
            </button>
          )
        })}
      </nav>

      <div className="h-5 w-px bg-border max-xl:hidden" aria-hidden />

      {fileName !== null && (
        <div className="flex min-w-0 items-center gap-2">
          <FileAudio className="size-4 shrink-0 text-muted-foreground" aria-hidden />
          <span className="num min-w-20 max-w-28 truncate text-xs xl:max-w-64" title={fileName}>
            {fileName}
          </span>
          <span className="shrink-0 rounded-[3px] border border-dashed border-border-strong px-1.5 text-2xs font-medium text-muted-foreground uppercase">
            {synthetic ? 'Synthetic' : 'Real'}
            <span className="max-2xl:sr-only"> recording</span>
          </span>
          {progress && (
            <span role="status" className="num flex shrink-0 items-center gap-1 text-2xs text-muted-foreground max-lg:hidden">
              <Loader2 className="size-3 animate-spin motion-reduce:animate-none" aria-hidden />
              Analysing {Math.min(progress.done + 1, progress.total)} of {progress.total}…
            </span>
          )}
        </div>
      )}

      <form onSubmit={submit} data-tour="open" className="flex shrink-0 items-center gap-1.5 max-lg:hidden">
        <label htmlFor="open-path" className="sr-only">
          Open a recording by path
        </label>
        <input
          id="open-path"
          type="text"
          value={path}
          onChange={(e) => setPath(e.target.value)}
          placeholder="Open a recording by path…"
          className="w-24 rounded-md border border-border-strong bg-surface px-2 xl:w-36 2xl:w-56 py-1 text-xs text-foreground placeholder:text-subtle-foreground"
        />
        <button
          type="submit"
          disabled={opening || !path.trim()}
          className="flex shrink-0 items-center gap-1 rounded-md border border-border-strong px-2 py-1 text-xs font-medium text-muted-foreground enabled:hover:bg-surface-2 enabled:hover:text-foreground disabled:opacity-40"
        >
          <FolderOpen className="size-3.5" aria-hidden />
          {opening ? 'Opening…' : 'Open'}
        </button>
        <label
          className="flex shrink-0 items-center gap-1 text-xs text-muted-foreground"
          title="Read numbered files (rec_000.cu8, rec_001.cu8, ...) as one recording. A folder is opened as a list of its recordings."
        >
          <input type="checkbox" checked={sequence} onChange={(e) => setSequence(e.target.checked)} />
          <span className="2xl:hidden">Join</span>
          <span className="max-2xl:hidden">Join numbered files</span>
        </label>
        <label
          className={`flex shrink-0 items-center gap-1 rounded-md border border-border-strong px-2 py-1 text-xs font-medium text-muted-foreground focus-within:ring-2 focus-within:ring-ring ${
            opening ? 'opacity-40' : 'cursor-pointer hover:bg-surface-2 hover:text-foreground'
          }`}
          title="Copy recording files into the workspace and open them. Drop files on the window works too."
        >
          <Upload className="size-3.5" aria-hidden />
          Upload
          <input
            type="file"
            multiple
            disabled={opening}
            className="sr-only"
            aria-label="Upload recording files"
            onChange={(e) => {
              const files = Array.from(e.target.files ?? [])
              e.target.value = '' // so choosing the same file again fires change
              if (files.length > 0) onUpload(files)
            }}
          />
        </label>
      </form>

      <div className="ml-auto flex items-center gap-2">
        {resultsUrl && (
          <div data-tour="export" className="flex">
            <ResultsExports
              resultsUrl={resultsUrl}
              sigmf={sigmf}
              onSaveSigmf={onSaveSigmf ?? (() => Promise.reject(new Error('Save as SigMF is not available')))}
            />
          </div>
        )}
        <span
          className="flex shrink-0 items-center gap-1.5 whitespace-nowrap rounded-full border px-2 py-0.5 text-2xs font-medium text-muted-foreground max-xl:hidden"
          title="This build loads nothing from the network: fonts, code and data are all bundled."
        >
          <WifiOff className="size-3" aria-hidden />
          <span className="max-2xl:sr-only">Offline build</span>
        </span>
        <button
          type="button"
          onClick={onHelp}
          title="What is Sanket? Replay the welcome and the guided tour"
          className="flex items-center gap-1 rounded-md px-2 py-1 text-xs font-medium text-muted-foreground hover:bg-surface-2 hover:text-foreground"
        >
          <CircleHelp className="size-3.5" aria-hidden />
          <span className="max-2xl:sr-only">Help</span>
        </button>
        <button
          type="button"
          onClick={toggle}
          className="grid size-8 place-items-center rounded-md text-muted-foreground hover:bg-surface-2 hover:text-foreground"
          aria-label={theme === 'dark' ? 'Switch to light theme' : 'Switch to dark theme'}
        >
          {theme === 'dark' ? <Sun className="size-4" /> : <Moon className="size-4" />}
        </button>
      </div>
    </header>
  )
}
