"""Opening a local recording, building its tile pyramid and running detection over it, all
kept in memory for this server process's lifetime (PLAN §5 M2). This is deliberately narrower
than the full job/workspace store PLAN §3 describes (SQLite, content-addressed artifacts, job
history): that is M7's scope. Here, a recording is opened once, and everything about it is held
in a dict - nothing is persisted across a restart. Opening returns once the tiles and the
detections exist; the decode chain over each detection then runs in the background
(`backend.jobs`), so the analyst sees the waterfall and the boxes long before the last report.
`app.py` is what turns `dsp.detect.detection_parameters`'s output into API-shaped evidence; the
results document is assembled by `backend.analysis` (used by `sanket analyse`), not here.
"""

import json
import uuid
from collections.abc import Callable
from concurrent.futures import ThreadPoolExecutor
from dataclasses import dataclass, replace
from pathlib import Path
from threading import RLock
from typing import Literal

from dsp.detect import Detection, detect
from dsp.evidence import Parameter
from dsp.ingest.dispatch import AnyRecording
from dsp.quality import capture_quality
from dsp.report import DetectionReport
from dsp.results import Assumptions, Results
from dsp.tiles import Pyramid, build_pyramid

from .analysis import (
    Entries,
    analyse_detection,
    assumptions_with,
    infer_sample_rate,
    numeric_rate,
    rate_note,
    results_of,
)
from .identity import recording_identity
from .inputs import RecordingError, expand, open_input
from .jobs import AnalysisJob, run_analysis
from .runrecord import Phase, PhaseTimer


def _survey(
    source: AnyRecording, *, real: bool, swap_iq: bool
) -> tuple[Pyramid, tuple[Detection, ...], tuple[Parameter, ...], tuple[Phase, ...]]:
    """The tile pyramid, the detections and the capture-quality parameters, each one streaming
    pass over the samples. Detection has its own FFT sizes, independent of the pyramid's: PLAN §5
    M2's "first tile <= 2 s" item is still open partly because of this second pass."""
    timer = PhaseTimer()
    with timer.phase("tiles"), source.reader(swap_iq=swap_iq) as reader:
        pyramid = build_pyramid(reader, real=real)
    with timer.phase("detect"), source.reader(swap_iq=swap_iq) as reader:
        detections = detect(reader, real=real).detections
    with timer.phase("capture-quality"), source.reader(swap_iq=swap_iq) as reader:
        quality = capture_quality(reader)
    return pyramid, detections, quality, tuple(timer.phases)


SYNTH_RECORDER = "sanket dsp.synth"


def sigmf_recorder(path: Path) -> str | None:
    """`core:recorder` from a .sigmf-meta file's global object; None for anything else."""
    if not path.name.lower().endswith(".sigmf-meta"):
        return None
    try:
        value = json.loads(path.read_text(encoding="utf-8")).get("global", {}).get("core:recorder")
    except (OSError, ValueError, AttributeError):
        return None
    return value if isinstance(value, str) else None


@dataclass(frozen=True)
class Recording:
    id: str
    path: Path
    container: str
    name: str
    source: AnyRecording
    num_samples: int
    real: bool
    pyramid: Pyramid
    detections: tuple[Detection, ...]
    job: AnalysisJob
    recorder: str | None = None  # what the file says wrote it (SigMF core:recorder), if it says
    # Values the analyst entered, by assumption name; each replaces the file's own entry.
    entered: Entries = ()
    # A sample rate the structural test supports for a file that states none (`infer_sample_rate`).
    inferred_rate: Parameter | None = None
    # What the samples say about the capture (`dsp.quality`), measured when the file was opened.
    quality: tuple[Parameter, ...] = ()
    # The files it was opened from (a path, or a sequence's files), for its content identity.
    files: tuple[Path, ...] = ()
    # How long opening took, phase by phase, for the run record.
    survey_phases: tuple[Phase, ...] = ()

    @property
    def swap_iq(self) -> bool:
        """The analyst says Q comes first: every read of the samples swaps the two."""
        return dict(self.entered).get("iq_order") == "QI"

    @property
    def assumptions(self) -> Assumptions:
        return assumptions_with(self.source.assumptions, self.entered, self.inferred_rate)

    @property
    def analyses(self) -> tuple[DetectionReport | None, ...]:
        """One entry per detection: its report, or None while it is still waiting or running."""
        return self.job.snapshot()

    @property
    def synthetic(self) -> bool:
        """The file states it was generated by Sanket's ground-truth lab (dsp.synth)."""
        return (self.recorder or "").startswith(SYNTH_RECORDER)


def results_for(recording: Recording) -> Results:
    """The results document of a recording whose analysis has finished (every detection has its
    report); the same one `sanket analyse` writes, byte for byte."""
    reports = [r for r in recording.analyses if r is not None]
    return results_of(
        recording.assumptions,
        recording_identity(
            recording.container, recording.num_samples, recording.files, recording.source
        ),
        len(recording.detections),
        reports,
        recording.quality,
    )


class RecordingStore:
    """Recordings opened this server run, by id. Not thread-per-request safe beyond the lock
    around registration; reads of an already-built `Recording` are safe (only its job fills in,
    behind its own lock)."""

    def __init__(self, on_done: Callable[[Recording], None] | None = None) -> None:
        # `on_done` runs on the worker thread when a recording's analysis finishes (not when it is
        # cancelled by a new assumption).
        self._on_done = on_done
        self._lock = RLock()
        self._recordings: dict[str, Recording] = {}
        # One worker: the chain is CPU-bound, and running one recording's detections in order
        # keeps the reports arriving top to bottom. Recordings opened meanwhile queue behind it.
        self._executor = ThreadPoolExecutor(max_workers=1, thread_name_prefix="analysis")

    def busy(self) -> bool:
        """An analysis is still running (closing now would lose it)."""
        with self._lock:
            return any(r.job.state == "running" for r in self._recordings.values())

    def close(self) -> None:
        """Stop background analysis: drop queued work, finish only the detection in flight."""
        with self._lock:
            recordings = list(self._recordings.values())
        for recording in recordings:
            recording.job.cancel()
        self._executor.shutdown(wait=False, cancel_futures=True)

    def open(self, path: Path, *, sequence: bool = False, datatype: str | None = None) -> Recording:
        """Open the one recording `path` names: a file, or with `sequence` the numbered files
        beside it as one. A folder is a batch, not a recording (`expand` lists it)."""
        items = expand(path, sequence=sequence)
        if len(items) != 1:
            raise RecordingError(
                f"{path} holds {len(items)} recordings; open one of them (or its numbered "
                "files as a sequence)"
            )
        if sequence and len(items[0].paths) == 1:
            raise RecordingError(f"{items[0].name} has no numbered siblings to join it to")
        opened = open_input(items[0], datatype)
        fmt = opened.recording.sample_format
        assert fmt is not None  # open_input raised for an UNKNOWN format
        real = not fmt.is_complex
        pyramid, detections, quality, phases = _survey(opened.recording, real=real, swap_iq=False)
        recording = Recording(
            id=str(uuid.uuid4()),
            path=path,
            container=opened.container,
            name=opened.name,
            source=opened.recording,
            num_samples=pyramid.samples,
            real=real,
            pyramid=pyramid,
            detections=detections,
            job=AnalysisJob(0),
            recorder=sigmf_recorder(path),
            inferred_rate=infer_sample_rate(opened.recording, detections),
            quality=quality,
            files=items[0].paths,
            survey_phases=phases,
        )
        return self._start(recording)

    def assume(
        self,
        recording_id: str,
        *,
        sample_rate: float | None = None,
        center_frequency: float | None = None,
        iq_order: Literal["IQ", "QI"] | None = None,
    ) -> Recording | None:
        """Take analyst-entered values (sample rate, centre frequency, IQ order) and analyse
        again.

        The tiles and detections are in fractions of the sample rate, so a rate or a centre
        frequency leaves them standing; what it changes is the boxes' units and whether the
        decode chain can run. An IQ order that swaps I and Q mirrors the spectrum, so the tiles
        and detections are built again. Returns None for an unknown id."""
        with self._lock:  # read, change and register as one step: overlapping calls both count
            current = self.get(recording_id)
            if current is None:
                return None
            if iq_order is not None and current.real:
                raise RecordingError("IQ order applies to complex samples; this recording is real")
            current.job.cancel()
            changes = dict(current.entered)
            if sample_rate is not None:
                changes["sample_rate"] = sample_rate
            if center_frequency is not None:
                changes["center_frequency"] = center_frequency
            if iq_order is not None:
                changes["iq_order"] = iq_order
            updated = replace(current, entered=tuple(changes.items()))
            if updated.swap_iq != current.swap_iq:
                pyramid, detections, quality, phases = _survey(
                    updated.source, real=False, swap_iq=updated.swap_iq
                )
                updated = replace(
                    updated,
                    pyramid=pyramid,
                    detections=detections,
                    quality=quality,
                    survey_phases=phases,
                )
            return self._start(updated)

    def _start(self, recording: Recording) -> Recording:
        """Register `recording` and analyse its detections in the background."""
        sample_rate = numeric_rate(recording.assumptions)
        # Boxes need a rate to be shown at all (`app.py`), so with none there is nothing to
        # analyse yet; entering one as an assumption starts it.
        detections = recording.detections
        job = AnalysisJob(len(detections) if sample_rate is not None else 0)
        recording = replace(recording, job=job)

        basis = rate_note(recording.assumptions)

        def analyse_one(index: int) -> DetectionReport:
            return analyse_detection(
                recording.source,
                detections[index],
                sample_rate=sample_rate,
                swap_iq=recording.swap_iq,
                rate_basis=basis,
            )

        with self._lock:
            self._recordings[recording.id] = recording
        if job.total:
            self._executor.submit(self._run, recording, analyse_one)
        return recording

    def _run(self, recording: Recording, analyse_one: Callable[[int], DetectionReport]) -> None:
        job = recording.job
        run_analysis(job, job.total, analyse_one)
        if self._on_done is not None and job.state == "done":
            self._on_done(recording)

    def get(self, recording_id: str) -> Recording | None:
        return self._recordings.get(recording_id)
