"""Opening a local recording, building its tile pyramid and running detection over it, all
kept in memory for this server process's lifetime (PLAN §5 M2). This is deliberately narrower
than the full job/workspace store PLAN §3 describes (SQLite, content-addressed artifacts, job
history): that is M7's scope. Here, a recording is opened once, and everything about it is held
in a dict - nothing is persisted across a restart, and there is no job runner. It exists so the
frontend's waterfall has real, server-computed tiles and detection boxes to switch to instead of
the demo texture (PLAN's M2 exit gate), without building ahead of that milestone's own scope.
`app.py` is what turns `dsp.detect.detection_parameters`'s output into API-shaped evidence; a
`dsp.results.Signal` per detection isn't assembled here, since that belongs to the real job
document M7 builds, not this bridge.
"""

import json
import uuid
from dataclasses import dataclass
from pathlib import Path
from threading import Lock

from dsp.analyse import analyse
from dsp.detect import Detection, detect, detection_parameters
from dsp.evidence import EvidenceLevel
from dsp.ingest.dispatch import NeedsDecompression, open_path
from dsp.report import DetectionReport, StageReport
from dsp.results import Assumptions
from dsp.tiles import Pyramid, build_pyramid


class RecordingError(ValueError):
    """A recording can't be opened or its format is not yet known well enough to tile it."""


def _failed_analysis(detection: Detection, error: str) -> DetectionReport:
    """`dsp.analyse.analyse` raised for this detection: report it honestly rather than failing
    the whole recording. The detect stage still stands (it's what produced the box); a second,
    failed stage carries the error, and the top-level level stays ESTIMATED - the level of the
    one stage that actually succeeded."""
    detect_stage = StageReport(
        id="detect",
        name="Detect",
        status="done",
        summary="Band found by the detector",
        level=EvidenceLevel.ESTIMATED,
        parameters=detection_parameters(detection),
    )
    failed_stage = StageReport(
        id="analyse",
        name="Analyse",
        status="failed",
        summary="Analysis raised an exception",
        error=error,
    )
    return DetectionReport(
        label="Signal",
        kind="unknown",
        level=EvidenceLevel.ESTIMATED,
        headline=f"Analysis failed: {error}",
        stages=(detect_stage, failed_stage),
        search=None,
        no_search_reason="Analysis failed before a search could run.",
        no_frames_reason="Analysis failed before any frames could be found.",
    )


SYNTH_RECORDER = "sanket dsp.synth"


def sigmf_recorder(path: Path) -> str | None:
    """`core:recorder` from a .sigmf-meta file's global object; None for anything else."""
    if not path.name.lower().endswith(".sigmf-meta"):
        return None
    try:
        value = json.loads(path.read_text(encoding="utf-8")).get("global", {}).get("core:recorder")
    except (OSError, ValueError, AttributeError):
        return None
    return value if isinstance(value, str) else None


@dataclass(frozen=True)
class Recording:
    id: str
    path: Path
    container: str
    name: str
    assumptions: Assumptions
    num_samples: int
    real: bool
    pyramid: Pyramid
    detections: tuple[Detection, ...]
    analyses: tuple[DetectionReport, ...]
    recorder: str | None = None  # what the file says wrote it (SigMF core:recorder), if it says

    @property
    def synthetic(self) -> bool:
        """The file states it was generated by Sanket's ground-truth lab (dsp.synth)."""
        return (self.recorder or "").startswith(SYNTH_RECORDER)


class RecordingStore:
    """Recordings opened this server run, by id. Not thread-per-request safe beyond the lock
    around registration; reads of an already-built `Recording` are safe (it's immutable)."""

    def __init__(self) -> None:
        self._lock = Lock()
        self._recordings: dict[str, Recording] = {}

    def open(self, path: Path) -> Recording:
        if not path.is_file():
            raise RecordingError(f"{path} is not a file")
        try:
            found = open_path(path)
        except NeedsDecompression as exc:
            raise RecordingError(str(exc)) from exc
        except ValueError as exc:
            raise RecordingError(f"could not read {path.name}: {exc}") from exc
        if len(found) != 1:
            raise RecordingError(
                f"{path.name} holds {len(found)} recordings; opening a multi-capture archive "
                "isn't supported yet, pick a single-capture file"
            )
        opened = found[0]
        fmt = opened.recording.sample_format
        if fmt is None:
            raise RecordingError(
                f"{path.name}'s sample format is unknown; resolve it before tiling "
                "(see the recording's Assumptions block)"
            )
        real = not fmt.is_complex
        with opened.recording.reader() as reader:
            pyramid = build_pyramid(reader, real=real)
        # A second streaming pass, at detect's own FFT sizes (independent of the pyramid's):
        # PLAN §5 M2's own "first tile <= 2 s" item is still open partly because of this - see
        # PLAN's M2 checklist.
        with opened.recording.reader() as reader:
            detections = detect(reader, real=real).detections
        assumptions = opened.recording.assumptions
        rate = assumptions.sample_rate.value
        sample_rate = rate if isinstance(rate, int | float) else None
        analyses = []
        for d in detections:
            try:
                with opened.recording.reader() as reader:
                    analyses.append(analyse(reader, d, sample_rate=sample_rate))
            except Exception as exc:  # one detection's failure mustn't sink the whole recording
                analyses.append(_failed_analysis(d, str(exc)))
        recording = Recording(
            id=str(uuid.uuid4()),
            path=path,
            container=opened.container,
            name=opened.name,
            assumptions=assumptions,
            num_samples=pyramid.samples,
            real=real,
            pyramid=pyramid,
            detections=detections,
            analyses=tuple(analyses),
            recorder=sigmf_recorder(path),
        )
        with self._lock:
            self._recordings[recording.id] = recording
        return recording

    def get(self, recording_id: str) -> Recording | None:
        return self._recordings.get(recording_id)
