"""Regenerate `dsp/src/dsp/fec/ldpc_data.py` from the files in `dsp/src/dsp/fec/ldpc_codes/`.

Development-time only: the product imports the generated module and never reads the reference
files. The numbers are parsed mechanically from the MIT-licensed files of two open-source
implementations (yairmz/ldpc for IEEE 802.11n, labrador-ldpc for CCSDS TC and TM); they are
parameters of the published standards (IEEE 802.11-2020 Annex F; CCSDS 231.1-O-1 and
CCSDS 131.0-B) but have not been compared with the standards' own tables, and no code from the
sources is used. Run `uv run python tools/gen_ldpc_data.py`.
"""

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "dsp" / "src" / "dsp" / "fec" / "ldpc_codes"
OUT = ROOT / "dsp" / "src" / "dsp" / "fec" / "ldpc_data.py"

HEADER = '''"""Published LDPC parity-check definitions: numbers only (generated, do not edit).

Generated by `tools/gen_ldpc_data.py`, which parses the two MIT-licensed implementations named
below. The tables describe these published codes:

* IEEE 802.11-2020 Annex F (clause 19.3.11.7, originally 802.11n-2009): the n = 648, Z = 27
  quasi-cyclic base matrices for rates 1/2, 2/3, 3/4 and 5/6. An entry is the cyclic shift of
  a Z x Z identity matrix (row r has its one in column (r + s) mod Z); -1 is the zero matrix.
* CCSDS 231.1-O-1 (TC synchronisation and channel coding, experimental LDPC codes): the
  (128, 64), (256, 128) and (512, 256) codes. M = n / 8 and H is 4 x 8 blocks of M x M; a block
  is the sum mod 2 of the right-circular shifts of I listed (an empty tuple is the zero block).
* CCSDS 131.0-B-5 section 7 (TM synchronisation and channel coding, AR4JA LDPC): the rate 1/2,
  2/3 and 4/5 prototype matrices, 3 x 5, 3 x 7 and 3 x 11 blocks of M x M. A block is the sum
  mod 2 of its terms: 0 is the identity I and k >= 1 is the permutation matrix Pi_k, the
  tables THETA and PHI below. PHI is keyed by M and indexed [j][k - 1].

Provenance: every number here was extracted mechanically from yairmz/ldpc (the `.qc` files,
MIT, Copyright (c) 2021 Yair M) for IEEE 802.11n and from labrador-ldpc
(`compact_parity_checks.rs`, MIT, Copyright 2017 Adam Greig) for the CCSDS codes. They were not
transcribed from the standards and have not been compared with the standards' PDFs; what checks
them is structural (code dimensions and full rank, systematic encoding, decoding to the exact
message) and labrador-ldpc's own edge-list checksums, which test the data against the file it was
generated from. Their licence texts are kept in `ldpc_codes/`. No code from either is used here.
"""

# ruff: noqa: E501
# fmt: off
'''


def parse_qc(path: Path) -> tuple[int, tuple[tuple[int, ...], ...]]:
    lines = [ln.split() for ln in path.read_text().splitlines() if ln.strip()]
    cols, rows, z = (int(x) for x in lines[0])
    base = tuple(tuple(int(x) for x in ln) for ln in lines[1:])
    assert len(base) == rows and all(len(r) == cols for r in base)
    return z, base


def array_bodies(text: str) -> dict[str, str]:
    """name -> the text of each `pub static NAME: ... = [ ... ];` initialiser."""
    out: dict[str, str] = {}
    for m in re.finditer(r"pub static (\w+): [^=]+=\s*(\[.*?\n?\]);", text, re.S):
        out[m.group(1)] = m.group(2)
    return out


def h_blocks(body: str, columns: int, *, tm: bool) -> tuple[tuple[tuple[int, ...], ...], ...]:
    """Block rows of block columns of the terms summed in each block (three layers added)."""
    layers = re.findall(r"\[\s*((?:\[[^\[\]]*\]\s*,?\s*){4})\]", body)
    assert len(layers) == 3, len(layers)
    grid: list[list[list[int]]] = [[[] for _ in range(columns)] for _ in range(4)]
    for layer in layers:
        rows = re.findall(r"\[([^\[\]]*)\]", layer)
        assert len(rows) == 4
        for r, row in enumerate(rows):
            tokens = [t.strip() for t in row.split(",") if t.strip()]
            assert len(tokens) == 11
            for c, tok in enumerate(tokens):
                if c >= columns:
                    assert tok in ("0", "HZ"), (c, tok)
                    continue
                term = parse_term(tok, tm=tm)
                if term is not None:
                    assert term not in grid[r][c], "duplicate term cancels"
                    grid[r][c].append(term)
    keep = 3 if tm else 4
    for r in range(keep, 4):
        assert all(not b for b in grid[r])
    return tuple(tuple(tuple(b) for b in grid[r]) for r in range(keep))


def parse_term(tok: str, *, tm: bool) -> int | None:
    if tok in ("0", "HZ"):
        return None
    if tok == "HI":
        return 0
    m = re.fullmatch(r"(HI|HP)\|\s*(\d+)", tok)
    assert m, tok
    n = int(m.group(2))
    if m.group(1) == "HI":
        return n  # TC: a circulant shift (TM never shifts I)
    assert tm
    return n + 1  # labrador's HP|n is the standard's Pi_(n+1)


def table(name: str, rows: tuple[object, ...]) -> str:
    return f"{name} = (\n" + "".join(f"    {row!r},\n" for row in rows) + ")\n"


def main() -> None:
    parts = [HEADER]

    parts.append("IEEE_802_11N_648_Z = 27\n")
    parts.append("# rate -> 12/8/6/4 block rows of 24 block columns; -1 is the zero block.\n")
    parts.append("IEEE_802_11N_648: dict[str, tuple[tuple[int, ...], ...]] = {\n")
    for rate, stem in (("1/2", "R12"), ("2/3", "R23"), ("3/4", "R34"), ("5/6", "R56")):
        z, base = parse_qc(SRC / "ieee802.11" / f"N648_{stem}.qc")
        assert z == 27
        parts.append(f'    "{rate}": (\n')
        parts += [f"        {row!r},\n" for row in base]
        parts.append("    ),\n")
    parts.append("}\n\n")

    text = (SRC / "ccsds_tc" / "compact_parity_checks.rs").read_text()
    bodies = array_bodies(text)

    parts.append(
        "# n -> 4 block rows x 8 block columns; a block is the tuple of shifts of I summed.\n"
    )
    parts.append("CCSDS_TC: dict[int, tuple[tuple[tuple[int, ...], ...], ...]] = {\n")
    for n in (128, 256, 512):
        blocks = h_blocks(bodies[f"TC{n}_H"], 8, tm=False)
        parts.append(f"    {n}: (\n")
        parts += [f"        {row!r},\n" for row in blocks]
        parts.append("    ),\n")
    parts.append("}\n\n")

    parts.append("# rate -> 3 block rows x (5, 7, 11) block columns; terms: 0 = I, k = Pi_k.\n")
    parts.append("CCSDS_TM: dict[str, tuple[tuple[tuple[int, ...], ...], ...]] = {\n")
    for rate, name, cols in (
        ("1/2", "TM_R12_H", 5),
        ("2/3", "TM_R23_H", 7),
        ("4/5", "TM_R45_H", 11),
    ):
        blocks = h_blocks(bodies[name], cols, tm=True)
        parts.append(f'    "{rate}": (\n')
        parts += [f"        {row!r},\n" for row in blocks]
        parts.append("    ),\n")
    parts.append("}\n\n")

    theta = [int(x) for x in re.findall(r"\d+", bodies["THETA_K"])]
    assert len(theta) == 26
    parts.append("# theta_k for k = 1 .. 26.\n")
    parts.append(f"CCSDS_TM_THETA = {tuple(theta)!r}\n\n")

    parts.append("# M -> phi_{j,k}(M) as [j][k - 1], j = 0 .. 3, k = 1 .. 26.\n")
    parts.append("CCSDS_TM_PHI: dict[int, tuple[tuple[int, ...], ...]] = {\n")
    for m in (128, 256, 512, 1024, 2048, 4096, 8192):
        rows = re.findall(r"\[([^\[\]]*)\]", bodies[f"PHI_J_K_M{m}"].strip()[1:-1])
        phi = tuple(tuple(int(x) for x in re.findall(r"\d+", r)) for r in rows)
        assert len(phi) == 4 and all(len(r) == 26 for r in phi)
        parts.append(f"    {m}: (\n")
        parts += [f"        {row!r},\n" for row in phi]
        parts.append("    ),\n")
    parts.append("}\n")
    parts.append("# fmt: on\n")
    OUT.write_text("".join(parts), encoding="utf-8", newline="\n")
    print(f"wrote {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
