/**
 * Client for the `/api/v1/recordings` and `/api/v1/tiles` routes (PLAN §5 M2): opening a real
 * recording and fetching its server-computed tile pyramid, in place of the synthetic demo
 * texture. See `dsp/tiles.py` for the tile contract this matches (row-major, fftshifted,
 * uint8-quantised dB) and `backend/src/backend/app.py` for the routes themselves.
 */
import type { DetectionReport } from './analysis'
import type { Box } from './box'
import type { Parameter } from './evidence'

export const TILE_ROWS = 256
export const TILE_COLS = 256

export interface LevelInfo {
  level: number
  rows: number
  cols: number
  rowSpan: number
}

export interface Assumptions {
  datatype: Parameter
  dataOffset: Parameter
  sampleRate: Parameter
  centerFrequency: Parameter
  iqOrder: Parameter | null
}

/** One detected signal's box, `detect`'s own evidence, and the full per-detection analysis
 * (PLAN M3-M6): estimate, sync, classify, demod, FEC and framing, as far as the chain
 * gets for this signal. */
export interface DetectionInfo {
  id: string
  box: Box
  parameters: Parameter[]
  /** Null while the background analysis hasn't reached this signal yet (see `AnalysisProgress`). */
  analysis: DetectionReport | null
}

/** How far the background analysis has got: `done` of `total` detections have a report. */
export interface AnalysisProgress {
  state: 'running' | 'done' | 'cancelled'
  done: number
  total: number
}

export interface RecordingInfo {
  id: string
  container: string
  name: string
  numSamples: number
  real: boolean
  /** SigMF `core:recorder`, as the file states it; null when it doesn't say. */
  recorder: string | null
  /** The file states it was generated by Sanket's ground-truth lab (dsp.synth). */
  synthetic: boolean
  fftSize: number
  /** Input samples per level-0 row (the FFT hop times the frames each row averages). */
  hop: number
  /** Hz; null when the Assumptions block leaves the sample rate UNKNOWN - never a default. */
  sampleRate: number | null
  dbMin: number
  dbMax: number
  /** Hz; null alongside sampleRate. */
  freqsHz: number[] | null
  /** The same axis as fractions of the sample rate; always present. */
  freqsNorm: number[]
  psdDb: number[]
  levels: LevelInfo[]
  assumptions: Assumptions
  /** What the samples say about the capture (clipping, DC offset, I/Q imbalance for a complex
   * recording, gaps), or one UNKNOWN when the file is empty. */
  captureQuality: Parameter[]
  analysis: AnalysisProgress
  /** What SigMF output the recording supports: 'save' a raw file (annotations, and a metadata
   * file written beside it), 'annotate' a SigMF recording (annotations only), else 'none'. */
  sigmf: 'annotate' | 'save' | 'none'
  /** Empty alongside sampleRate: a box in seconds/Hz needs a known rate, same as freqsHz. */
  detections: DetectionInfo[]
}

export class ApiError extends Error {
  /** Set when the sample format is UNKNOWN: the sniffer's candidates, possibly none. */
  formatCandidates: string[] | null = null
}

async function asJson<T>(response: Response): Promise<T> {
  if (!response.ok) {
    const body: unknown = await response.json().catch(() => null)
    const detail = typeof body === 'object' && body && 'detail' in body ? String(body.detail) : null
    const error = new ApiError(detail ?? `request failed: ${response.status} ${response.statusText}`)
    if (typeof body === 'object' && body && 'formatCandidates' in body && Array.isArray(body.formatCandidates)) {
      error.formatCandidates = body.formatCandidates.map(String)
    }
    throw error
  }
  return response.json() as Promise<T>
}

/** One recording a path names: a file, or several numbered files read as one. */
export interface InputInfo {
  /** The file to open; the first of them for a sequence. */
  path: string
  name: string
  files: number
  sequence: boolean
}

/** What a path names, without reading any samples: a file is itself, a folder is a batch of its
 * files. `sequence` joins numbered files (rec_000.cu8, rec_001.cu8, ...) into one recording each. */
export async function listInputs(path: string, sequence = false): Promise<InputInfo[]> {
  const response = await fetch('/api/v1/inputs', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ path, sequence }),
  })
  return asJson<InputInfo[]>(response)
}

/** `datatype` is the analyst's choice of sample format for a raw file the sniffer can't read
 * (an ApiError with `formatCandidates` says when); the server records it as entered. */
export async function openRecording(path: string, sequence = false, datatype?: string): Promise<RecordingInfo> {
  const response = await fetch('/api/v1/recordings', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ path, sequence, datatype }),
  })
  return asJson<RecordingInfo>(response)
}

/** What the analyst can enter for a recording; the server restarts the analysis with it. */
export interface AssumptionValues {
  sampleRate?: number
  centerFrequency?: number
  /** 'QI' swaps the two components, which mirrors the spectrum; the samples can't tell them apart. */
  iqOrder?: 'IQ' | 'QI'
}

/** Values the analyst enters for what the file leaves UNKNOWN (or gets wrong). */
export async function putAssumptions(id: string, values: AssumptionValues): Promise<RecordingInfo> {
  const response = await fetch(`/api/v1/recordings/${id}/assumptions`, {
    method: 'PUT',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(values),
  })
  return asJson<RecordingInfo>(response)
}

/** The file to open from an upload: the SigMF metadata if there is one (its data file rides
 * along), otherwise the first file that is not a SigMF data file. */
export function mainUpload(files: readonly File[]): File | undefined {
  return (
    files.find((f) => f.name.toLowerCase().endsWith('.sigmf-meta')) ??
    files.find((f) => !f.name.toLowerCase().endsWith('.sigmf-data')) ??
    files[0]
  )
}

/** Sends `files` to the server's workspace as one batch, each streamed as it is (never read
 * whole into memory), and returns the server path of the main one, ready for `openRecording`. */
export async function uploadFiles(files: readonly File[]): Promise<string> {
  const main = mainUpload(files)
  if (!main) throw new ApiError('no files to upload')
  const batch = crypto.randomUUID().replaceAll('-', '')
  let mainPath = ''
  // The main file goes last so its path is the last reply, and a SigMF data file is already
  // there when its metadata arrives.
  for (const file of [...files.filter((f) => f !== main), main]) {
    const response = await fetch(`/api/v1/uploads/${batch}/${encodeURIComponent(file.name)}`, {
      method: 'PUT',
      body: file,
    })
    const uploaded = await asJson<{ path: string }>(response)
    if (file === main) mainPath = uploaded.path
  }
  return mainPath
}

/** Save as SigMF: the server writes `<name>.sigmf-meta` beside a raw file (never touching the
 * samples) and returns where. Rejects with the server's own text for a recording that isn't raw
 * (422) or whose metadata file already exists (409). */
export async function saveAsSigmf(id: string): Promise<string> {
  const response = await fetch(`/api/v1/recordings/${id}/sigmf`, { method: 'POST' })
  return (await asJson<{ path: string }>(response)).path
}

/** One finished analysis the server kept in its workspace (`GET /api/v1/history`, newest first). */
export interface HistoryEntry {
  id: string
  /** When the analysis finished, UTC, `YYYY-MM-DDTHH:MM:SSZ`. */
  createdUtc: string
  name: string
  container: string
  signals: number
  /** How many of the signals have a VERIFIED headline. */
  verified: number
  /** SHA-256 of the results document, as hex. */
  resultsSha256: string
}

/** The analyses kept in the workspace, newest first; they survive a server restart. */
export async function fetchHistory(): Promise<HistoryEntry[]> {
  return asJson<HistoryEntry[]>(await fetch('/api/v1/history'))
}

/** Deletes a kept analysis and everything derived from it. Rejects with the server's own text
 * (404 "no such analysis" when it is already gone). */
export async function deleteHistory(id: string): Promise<void> {
  const response = await fetch(`/api/v1/history/${encodeURIComponent(id)}`, { method: 'DELETE' })
  if (!response.ok) await asJson(response) // always throws, with the server's detail
}

export async function getRecording(id: string): Promise<RecordingInfo> {
  return asJson<RecordingInfo>(await fetch(`/api/v1/recordings/${id}`))
}

/**
 * Listens to a recording's analysis progress until it is done. `onProgress` fires for each event
 * (the caller refetches the recording for the new reports); `onError` fires once if the stream
 * fails, after which nothing more is delivered. Returns a function that stops listening. Closing
 * on `done` matters: the server ends the stream then, and an EventSource would reconnect to it.
 */
export function watchAnalysis(
  id: string,
  onProgress: (progress: AnalysisProgress) => void,
  onError: () => void,
): () => void {
  const source = new EventSource(`/api/v1/recordings/${id}/events`)
  source.addEventListener('progress', (event) => {
    const progress = JSON.parse((event as MessageEvent<string>).data) as AnalysisProgress
    if (progress.state !== 'running') source.close()
    onProgress(progress)
  })
  source.onerror = () => {
    source.close()
    onError()
  }
  return () => source.close()
}

interface Tile {
  rows: number
  cols: number
  data: Uint8Array
}

async function fetchTile(recordingId: string, level: number, row: number, col: number): Promise<Tile> {
  const response = await fetch(`/api/v1/tiles/${recordingId}/${level}/${row}/${col}`)
  if (!response.ok) throw new ApiError(`failed to fetch tile ${level}/${row}/${col}`)
  const rows = Number(response.headers.get('x-tile-rows') ?? 0)
  const cols = Number(response.headers.get('x-tile-cols') ?? 0)
  const data = new Uint8Array(await response.arrayBuffer())
  return { rows, cols, data }
}

/** A level's whole grid, stitched from its fixed-size tiles (row-major, matching `dsp.tiles`). */
export async function fetchLevelGrid(recordingId: string, level: LevelInfo): Promise<Uint8Array> {
  const rowTiles = Math.max(1, Math.ceil(level.rows / TILE_ROWS))
  const colTiles = Math.max(1, Math.ceil(level.cols / TILE_COLS))
  const grid = new Uint8Array(level.rows * level.cols)
  const requests: Promise<void>[] = []
  for (let rt = 0; rt < rowTiles; rt++) {
    for (let ct = 0; ct < colTiles; ct++) {
      requests.push(
        fetchTile(recordingId, level.level, rt, ct).then((tile) => {
          for (let r = 0; r < tile.rows; r++) {
            const destStart = (rt * TILE_ROWS + r) * level.cols + ct * TILE_COLS
            grid.set(tile.data.subarray(r * tile.cols, (r + 1) * tile.cols), destStart)
          }
        }),
      )
    }
  }
  await Promise.all(requests)
  return grid
}
